title: Farah Kamila
#show_downloads: true
logo: /assets/img/Headshot_LinkedIn.jpg
description: 
<a href="/resume/" class="download">Resume</a>
<a href="/projects/" class="download">Projects & Samples</a>
theme: jekyll-theme-minimal
