title: Farah Kamila
#show_downloads: true
logo: /assets/img/Headshot_LinkedIn.jpg
description: |
  <a href="/assets/pdf/Resume_250526_Sci.pdf" class="button">Resume</a>
  <a href="/projects/" class="button">Projects & Samples</a>
theme: jekyll-theme-minimal
